# Generated by Django 3.1.13 on 2022-05-01 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('L', 'Language'), ('F', 'Framework'), ('L', 'Library or Package')], default='L', max_length=40)),
                ('parents', models.ManyToManyField(related_name='_technology_parents_+', to='app.Technology')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='John', max_length=100)),
                ('last_name', models.CharField(default='Doe', max_length=100)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, default='images/smiley.jpg', upload_to='images/')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('tech_roadmap', models.ManyToManyField(blank=True, null=True, to='app.Technology')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('E', 'Exploration'), ('P', 'Project'), ('L', 'Learning'), ('H', 'Hackathon'), ('E', 'Event')], default='E', max_length=40)),
                ('description', models.TextField(blank=True, null=True)),
                ('likes_amount', models.IntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('project_link', models.CharField(blank=True, max_length=2000, null=True)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile')),
                ('technologies', models.ManyToManyField(to='app.Technology')),
            ],
        ),
    ]
