# Generated by Django 3.1.13 on 2022-04-28 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='Profile-PNG-File.png', upload_to='images/'),
        ),
    ]
