# Generated by Django 3.1.13 on 2022-04-30 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Difficulty',
        ),
    ]
