# Generated by Django 3.1.13 on 2022-04-23 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='difficulty',
        ),
    ]
